/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tkoba' at '16/03/18 22:31' with Gradle 2.12
 *
 * @author tkoba, @date 16/03/18 22:31
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
